### ISSUE TITLE
Illegal Characters in path

### ISSUE THREAD

**Issue by WSADKeysGaming** [imPRAGMA/W2XKit#1]
Target Height (e.x. 1080):
1840
Noise Level (0, 1, 2 or 3) [2 recommended]:
2
Threads (e.x. 1, 2, 5, 20) [Nothing more than 20 recommended, each thread can take up to 500mb of memory, 18 threads takes up roughly 8-9gb of ram]:
10
Do you want to extract frames? [y/n]
y
Do you want to upscale frames? [y/n] - extracted frames must already exist
y
Do you want to combine frames? [y/n] - upscaled frames must already exist
y

Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at PRAGMAsW2XKit.Program.Main(String[] args)

other notes: Video name was "wew.mp4"

**Comment by imPRAGMA** [comment]
Seems like for input file path you put a path like "wew.mp4" and not "C:\Users\PRAGMA\Documents\videos\wew.mp4" it has to be absolute not relative.
